spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/constro
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Optional: Configure the Hibernate second-level cache
  cache:
    use_second_level_cache: true
    use_query_cache: false
    region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

  # Optional: Configure the naming strategy
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace

# Optional: Server settings
server:
  port: 8080




